// Generated by CoffeeScript 1.4.0
(function() {
  var IPInfoDB, ipinfodb;

  IPInfoDB = function(ipInfoDbApiKey) {
    this.request = require('request');
    this.ipInfoDbApiKey = ipInfoDbApiKey;
    this.getMyLocation = function(callback) {
      return this.getLocation(void 0, callback);
    };
    this.getLocation = function(ipAddress, callback) {
      var requestURL;
      requestURL = 'http://api.ipinfodb.com/v3/ip-city/?format=json&key=' + this.ipInfoDbApiKey;
      if (ipAddress) {
        requestURL += '&ip=' + ipAddress;
      }
      return this.request(requestURL, function(error, response, body) {
        if (!error && response.statusCode === 200) {
          callback(null, body);
          return;
        }
        return callback(error);
      });
    };
    return this;
  };

  ipinfodb = new IPInfoDB('23c6760303d8c4873fdc36c67a04d384104e14f6a1904a83c2e93e03e0b5e857');

  ipinfodb.getMyLocation(function(err, body) {
    return console.log(body);
  });

}).call(this);
