// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = (function() {

    function exports(ipInfoDbApiKey) {
      this.ipInfoDbApiKey = ipInfoDbApiKey;
      this.getLocation = __bind(this.getLocation, this);

      this.getMyLocation = __bind(this.getMyLocation, this);

      this.request = require('request');
    }

    exports.prototype.getMyLocation = function(callback) {
      return this.getLocation(void 0, callback);
    };

    exports.prototype.getLocation = function(ipAddress, callback) {
      var requestURL;
      requestURL = 'http://api.ipinfodb.com/v3/ip-city/?format=json&key=' + this.ipInfoDbApiKey;
      if (ipAddress != null) {
        requestURL += '&ip=' + ipAddress;
      }
      return this.request(requestURL, function(error, response, body) {
        if (!error && response.statusCode === 200) {
          callback(null, JSON.parse(body));
          return;
        }
        return callback(error);
      });
    };

    return exports;

  })();

}).call(this);
