// Generated by CoffeeScript 1.4.0
(function() {

  exports.IPInfoDB = function(ipInfoDbApiKey) {
    this.request = require('request');
    this.ipInfoDbApiKey = ipInfoDbApiKey;
    this.getMyLocation = function(callback) {
      return this.getLocation(void 0, callback);
    };
    this.getLocation = function(ipAddress, callback) {
      var requestURL;
      requestURL = 'http://api.ipinfodb.com/v3/ip-city/?format=json&key=' + this.ipInfoDbApiKey;
      if (ipAddress) {
        requestURL += '&ip=' + ipAddress;
      }
      return this.request(requestURL, function(error, response, body) {
        if (!error && response.statusCode === 200) {
          callback(null, body);
          return;
        }
        return callback(error);
      });
    };
    return this;
  };

}).call(this);
